randocafe/catalog/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.profile, name="profile"),
    path("done/", views.done, name="done"),
    path("trips/", views.TripListView.as_view(), name="trips"),
    re_path(r"^trip/(?P<pk>\d+)$", views.TripDetailView.as_view(), name="trip-detail"),
    path("trip/create/", views.TripCreate.as_view(), name="trip-create"),
    path("trip/<int:pk>/update/", views.TripUpdate.as_view(), name="trip-update"),
    path("trip/<int:pk>/delete/", views.tripSoftDelete, name="trip-delete"),
    path("tripinstances/", views.TripInstanceListView.as_view(), name="tripinstances"),
    path(
        "tripinstance/<uuid:pk>",
        views.TripInstanceDetailView.as_view(),
        name="tripinstance-detail",
    ),
    path(
        "tripinstance/create/",
        views.TripInstanceCreate.as_view(),
        name="tripinstance-create",
    ),
    path(
        "tripinstance/<uuid:pk>/update/",
        views.TripInstanceUpdate.as_view(),
        name="tripinstance-update",
    ),
    path(
        "tripinstance/<uuid:pk>/delete/",
        views.TripInstanceDelete.as_view(),
        name="tripinstance-delete",
    ),
    path("mytrips/", views.BookedTripByUserListView.as_view(), name="mytrips"),
    path(
        "managedtrips/",
        views.AllManagedTripsListView.as_view(),
        name="managed-trips",
    ),
    path(
        "pendingtrips/",
        views.PendingTripsListView.as_view(),
        name="pending-trips",
    ),
    path(
        "inprogresstrips/",
        views.InProgressTripsListView.as_view(),
        name="inprogress-trips",
    ),
    path(
        "bookedtrips/",
        views.BookedTripsListView.as_view(),
        name="booked-trips",
    ),
    path(
        "archivedtrips/",
        views.ArchivedTripsListView.as_view(),
        name="archived-trips",
    ),
    path(
        "trip/<uuid:pk>/extend/",
        views.extend_trip_employee,
        name="extend-trip-employee",
    ),
    path("clients/", views.ClientListView.as_view(), name="clients"),
    path("client/<uuid:pk>", views.ClientDetailView.as_view(), name="client-detail"),
    path("client/create/", views.ClientCreate.as_view(), name="client-create"),
    path(
        "client/<uuid:pk>/update/", views.ClientUpdate.as_view(), name="client-update"
    ),
    path(
        "client/<uuid:pk>/delete/", views.ClientDelete.as_view(), name="client-delete"
    ),
    path("hikings/", views.HikingListView.as_view(), name="hikings"),
    re_path(
        r"^hiking/(?P<pk>\d+)$", views.HikingDetailView.as_view(), name="hiking-detail"
    ),
    path("hiking/create/", views.HikingCreate.as_view(), name="hiking-create"),
    path("hiking/<int:pk>/update/", views.HikingUpdate.as_view(), name="hiking-update"),
    path("hiking/<int:pk>/delete/", views.HikingDelete.as_view(), name="hiking-delete"),
    path("roasters/", views.RoasterListView.as_view(), name="roasters"),
    path("roaster/<uuid:pk>", views.RoasterDetailView.as_view(), name="roaster-detail"),
    path(
        "roaster/create/",
        views.RoasterCreate.as_view(),
        name="roaster-create",
    ),
    path(
        "roaster/<uuid:pk>/update/",
        views.RoasterUpdate.as_view(),
        name="roaster-update",
    ),
    path(
        "roaster/<uuid:pk>/delete/",
        views.RoasterDelete.as_view(),
        name="roaster-delete",
    ),
    path("map/", views.MarkersMapView.as_view(), name="map"),
    path("markers/", views.MarkerListView.as_view(), name="markers"),
    re_path(
        r"^marker/(?P<pk>\d+)$", views.MarkerDetailView.as_view(), name="marker-detail"
    ),
    # path("apiregister/", views.APIRegisterView.as_view(), name='api-register'),
    path(
        "token/obtain/",
        views.EmailTokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    # path("token/refresh/", TokenRefreshView.as_view(), name="token-refresh"),
]

randocafe/randocafe/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("randocafe/api/v1/", include("catalog.api")),
    path("randocafe/admin/", admin.site.urls),
    path("randocafe/catalog/", include("catalog.urls")),
    path("", RedirectView.as_view(url="randocafe/catalog/")),
    path("randocafe/accounts/", include("django.contrib.auth.urls")),
]

randocafe/catalog/models.py
import uuid
from datetime import date

from django.contrib.auth.models import AbstractUser
from django.contrib.gis.db import models as gis_models
from django.db import models
from django.urls import reverse

from .managers import SoftDeleteManager, UserManager


class SoftDeleteModel(models.Model):
    is_deleted = models.BooleanField(default=False)
    objects = SoftDeleteManager()
    all_objects = models.Manager()

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def restore(self):
        self.is_deleted = False
        self.save()

    class Meta:
        abstract = True


class MyUser(AbstractUser):
    """Model representing a custom user"""

    username = None
    email = models.EmailField(max_length=100, unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self) -> str:
        """String for representing the model object"""
        return f"{self.email}"


class Author(models.Model):
    """Model representing a trip author"""

    user = models.OneToOneField(MyUser, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ["user__last_name"]

    def get_absolute_url(self):
        """Return the url to access a particular Author instance"""
        return reverse("author-details", args=[str(self.id)])

    def __str__(self) -> str:
        """String for representing the model object"""
        return f"{self.user.first_name}, {self.user.last_name}"


class Client(models.Model):
    """Model representing a client"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID unique")

    first_name = models.CharField(max_length=200, help_text="Prénom")
    last_name = models.CharField(max_length=200, help_text="Nom")

    date_of_birth = models.DateField(help_text="Format date : [aaaa-mm-jj]")

    # user = models.OneToOneField(MyUser, on_delete=models.SET_NULL, null=True)

    PARTICIPANT_STATUS = (("l", "leader"), ("f", "follower"))

    status = models.CharField(
        max_length=1,
        choices=PARTICIPANT_STATUS,
        blank=True,
        default="f",
        help_text="Statut du participant",
    )

    def get_absolute_url(self):
        """Return the url to access a particular Client instance"""
        return reverse("client-detail", args=[str(self.id)])

    def __str__(self) -> str:
        """String for representing the model object"""
        return f"{self.first_name}, {self.last_name}"


class Type(models.Model):
    """Model representing a hiking type"""

    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name


'''
class Level(models.Model):
    """Model representing a hiking level"""

    LEVEL_NAME = (("e", "easy"), ("m", "medium"), ("d", "difficult"))

    name = models.CharField(
        max_length=1,
        choices=LEVEL_NAME,
        blank=True,
        default="e",
        help_text="Hiking level",
    )

    def __str__(self) -> str:
        return self.name
'''


class Coffee(models.Model):
    """Model representing a coffee"""

    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name


class Marker(models.Model):
    """Model representing a marker"""

    name = models.CharField(max_length=255)
    location = gis_models.PointField()

    def get_absolute_url(self):
        """Return the url to access a particular marker instance"""
        return reverse("marker-detail", args=[str(self.id)])

    def __str__(self) -> str:
        return self.name


class Roaster(models.Model):
    """Model representing a roaster"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID unique")

    name = models.CharField(max_length=200, help_text="Nom")
    address = models.CharField(max_length=300, help_text="Adresse du torréfacteur")
    marker = models.ForeignKey(
        Marker,
        on_delete=models.SET_NULL,
        null=True,
        help_text="Sélectionner un géo-marqueur",
    )
    description = models.TextField(
        max_length=1000, help_text="Entrer une description du torréfacteur"
    )

    coffee = models.ManyToManyField(
        Coffee, help_text="Sélectionner les cafés diponibles"
    )

    def get_absolute_url(self):
        """Return the url to access a particular Roaster instance"""
        return reverse("roaster-detail", args=[str(self.id)])

    def __str__(self) -> str:
        """String for representing the model object"""
        return f"{self.name}"


class Hiking(models.Model):
    """Model representing a hiking"""

    name = models.CharField(max_length=200, help_text="Nom")
    description = models.TextField(
        max_length=1000, help_text="Donner une description de la randonnée"
    )

    # level = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True)
    marker = models.ForeignKey(
        Marker,
        on_delete=models.SET_NULL,
        null=True,
        help_text="Attribuer un géo-marqueur",
    )
    # type = models.ManyToManyField(Type, help_text="Select type(s) for this hiking")
    type = models.ManyToManyField(
        Type,
        help_text='Sélectionner un ou des types de randonnée, i.e. "Ville", "Forêt", "Mer" ...',
    )

    LEVEL_NAME = (("e", "easy"), ("m", "medium"), ("d", "difficult"))

    level = models.CharField(
        max_length=1,
        choices=LEVEL_NAME,
        blank=True,
        default="e",
        help_text='Niveau de difficulté de la randonnée, i.e. "Facile", "Moyen", "Difficile"',
    )

    roaster = models.OneToOneField(
        Roaster, on_delete=models.SET_NULL, null=True, help_text="Torréfacteur"
    )

    '''
    def display_level(self):
        """Create a string for the Level."""
        return ", ".join(level.name for level in self.level.all()[:3])

    display_level.short_description = "Level"
    '''

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this hiking."""
        return reverse("hiking-detail", args=[str(self.id)])

    def display_type(self):
        """Create a string for the type."""
        return ", ".join(type.name for type in self.type.all()[:3])

    display_type.short_description = "Type"

    def __str__(self) -> str:
        """String for representing the Model object."""
        return self.name


class Trip(SoftDeleteModel):
    """Model representing a trip"""

    name = models.CharField(max_length=150, help_text="Nom")
    created = models.DateTimeField(auto_now=True)
    description = models.TextField(
        max_length=1000, help_text="Entrer une courte description du trip"
    )

    author = models.ForeignKey(
        Author, on_delete=models.SET_NULL, null=True, help_text="Auteur de ce trip"
    )
    hiking = models.ForeignKey(
        Hiking,
        on_delete=models.SET_NULL,
        null=True,
        help_text="Sélectionner une randonnée pour ce trip",
    )

    class Meta:
        ordering = ["name", "created"]

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this trip."""
        return reverse("trip-detail", args=[str(self.id)])

    def __str__(self) -> str:
        """String for representing the Model object."""
        return self.name


class TripInstance(models.Model):
    """Model representing an instance of a trip"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="ID unique pour une instance spécipfique d'un trip",
    )

    clients = models.ManyToManyField(
        Client, help_text="Sélectionner une liste de clients"
    )
    created = models.DateTimeField(auto_now=True)
    start_date = models.DateField(help_text="Format date : [aaaa-mm-jj]")
    end_date = models.DateField(help_text="Format date : [aaaa-mm-jj]")

    trip = models.ForeignKey(
        Trip,
        on_delete=models.RESTRICT,
        null=True,
        help_text="Sélectionner un trip existant",
    )

    owner = models.ForeignKey(
        MyUser,
        on_delete=models.RESTRICT,
        null=True,
        help_text="Sélectionner un propriétaire pour cette réservation",
    )

    BOOKING_STATUS = (
        ("b", "booked"),
        ("f", "finished"),
        ("i", "in progress"),
        ("p", "pending"),
    )

    status = models.CharField(
        max_length=1,
        choices=BOOKING_STATUS,
        blank=True,
        default="p",
        help_text="Status de la réservation",
    )

    @property
    def passed_deadline(self):
        """Determines if the trip have passed the deadline"""
        return bool(self.end_date and date.today() > self.end_date)

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this trip instance."""
        return reverse("tripinstance-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.id} ({self.trip.name})"

    class Meta:
        ordering = ["created"]
        permissions = (
            ("can_list_all_instances", "List all trip instances"),
            ("can_list_own_instances", "List own trip instance"),
            ("can_list_pending_instance", "List pending trip instance"),
            ("can_list_inprogress_instance", "List in progress trip instance"),
            ("can_list_booked_instance", "List booked trip instance"),
            ("can_list_archived_instance", "List archived trip instance"),
        )

randocafe/catalog/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from .models import MyUser, Trip, TripInstance


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = MyUser
        fields = ("email",)


class ExtendTripForm(forms.Form):
    extend_date = forms.DateField(
        help_text="Enter a date between now and 2 weeks (default = 1)."
    )

    def clean_extend_date(self):
        data = self.cleaned_data["extend_date"]

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))

        # Check if a date is in the allowed range (+2 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=2):
            raise ValidationError(_("Invalid date - renewal more than 2 weeks ahead"))

        # Remember to always return the cleaned data.
        return data


class ExtendTripModelForm(ModelForm):
    def clean_end_date(self):
        data = self.cleaned_data["end_date"]

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))

        # Check if a date is in the allowed range (+2 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=2):
            raise ValidationError(_("Invalid date - extend more than 2 weeks ahead"))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = TripInstance
        fields = ["end_date"]
        labels = {"end_date": _("Extend date")}
        help_texts = {
            "end_date": _("Enter a date between now and 2 weeks (default 1).")
        }


class TripInstanceModelForm(ModelForm):
    def clean_end_date(self):
        data = self.cleaned_data["end_date"]
        data_start = self.cleaned_data["star_date"]

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(
                _("Date invalide - ne peut pas être antérieure à aujourd'hui.")
            )

        # Check if a date isn't previous to the start date
        if data < data_start:
            raise ValidationError(
                _(
                    "Date invalide - ne peut pas être antérieure à la date de début de réservation."
                )
            )

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = TripInstance
        fields = ["end_date"]


class TripDeleteForm(ModelForm):
    class Meta:
        model = Trip
        fields = ("is_deleted",)

randocafe/catalog/templates/catalog/client_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Supprimer ce client ?</h1>

<p>Êtes vous certain de vouloir supprimer ce client de la base de données : {{client.first_name}}, {{client.last_name}} - ({{ client.id }}) ?</p>

<form action="" method="POST" class="formDelete">
  {% csrf_token %}
  <input type="submit" value="Oui, supprimer" class="btnDelConf"/>
  <a href="{% url 'clients' %}" class="btnCA">Annuler</a>
</form>

{% endblock %}

randocafe/catalog/templates/catalog/client_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Formulaire d'édition d'un client</h1>
<form action="" method="post" class="tptForm">
  {% csrf_token %}
  <table>
    <tbody class="tabForm">
      <tr>
        <td>
          {{ form.as_table }}
        </td>
      </tr>
    </tbody>
  </table>
  <div class="btnForm">
    <input type="submit" value="Confirmer" />
    <a href="{% url 'clients' %}">Annuler</a>
  </div>
</form>
{% endblock %}

randocafe/catalog/templates/catalog/done.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Opération réalisée avec succès.</h1>
  <div class="btnCA">
    <a href="{% url 'index' %}">Retour Accueil ?</a>
  </div>
{% endblock %}

randocafe/catalog/templates/catalog/extend_trip_employee.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Extend : {{ trip_instance.trip.name }}</h1>
  <p>Owner : {{ trip_instance.trip.author }}</p>
  <p {% if trip_instance.passed_dealine %} class="text-danger"{% endif %} >End date : {{ trip_instance.end_date}}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

randocafe/catalog/templates/catalog/hiking_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Liste des randonnées</h1>
  <div class="listView">
    {% if hiking_list %}
    <table>
      <tbody class="tableView">
        {% for hiking in hiking_list %}
        <tr class="tableViewIdent">
            <td>
              {{ hiking.name }}
              , (Localisation : {{hiking.marker}})
            </td>
        </tr>
        <tr class="tableViewBtn">
            <td>
              <button class="btnR">
                <a href="{{ hiking.get_absolute_url }}"> Voir</a>
              </button>
            </td>
            <td>
              <button class="btnU">
                <a href="{% url 'hiking-update' hiking.pk %}"> Modifier</a>
              </button>
            </td>
            <td>
              <button class="btnD">
                <a href="{% url 'hiking-delete' hiking.pk%}"> Supprimer</a>
              </button>
            </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>Vous n'avez pas encore de randonnée.</p>
    {% endif %}

    <button class="btnC">
        <a href="{% url 'hiking-create' %}">Ajouter une randonnée</a>
    </button>
  </div>
{% endblock %}

randocafe/catalog/templates/catalog/map.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Une carte avec nos randonnées</h1>
<div id="map" class="mapBig">
</div>
{% load static %}
<script src="{% static 'js/map.js' %}" defer></script>
{% endblock %}

randocafe/catalog/templates/catalog/marker_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Marqueur : {{ marker.name }}</h1>

  <p>Location : {{ marker.location }}</p>

  <p>Localisation :</p>
  <div class="mapHiking">

    <div id="map" class="mapHiking">
    </div>
  </div>
{% endblock %}

randocafe/catalog/templates/catalog/marker_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Liste des géo-marqueurs</h1>
  <div class="listView">
    {% if marker_list %}
    <table>
      <tbody class="tableView">
        {% for marker in marker_list %}
        <tr class="tableViewIdent">
            <td>
              {{ marker.name }}, {{ marker.location }}
            </td>
        </tr>
        <tr class="tableViewBtn">
            <td>
              <button class="btnR">
                <a href="{{ marker.get_absolute_url }}"> Voir</a>
              </button>
            </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>Vous n'avez pas encore de géo-marqueur.</p>
    {% endif %}
  </div>
{% endblock %}

randocafe/catalog/templates/catalog/profile.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Vous êtes connecté(e) en tant que : {{ user.get_username }}</h1>
  <hr>
  <div class="padMargSoft">
    <h4>Accéder directement à vos réservations (statut = planifié)</h4>
    {% if perms.catalog.can_list_own_instances %}
    <a href="{% url 'mytrips' %}" class="linkProfile">Mes trips planifiés</a></li>
    {% else %}
    <p class="text-warning">Vous n'avez pas accès à cette fonctionnalité.</p>
    {% endif %}
  </div>
  <div class="padMargSoft">
    <h4> Accéder directement à l'historique de toutes les réservations</h4>
    {% if perms.catalog.can_list_all_instances %}
    <a href="{% url 'managed-trips' %}" class="linkProfile">Historiques des trips</a></li>
    {% else %}
    <p class="text-warning">Vous n'avez pas accès à cette fonctionnalité.</p>
    {% endif %}
  </div>
  <hr>
  <div>
    {% if perms.catalog.can_list_own_instances %}
    <p>Il est nécessaire de récupérer un jeton d'authentification pour utiliser les données géograhique dans le service Rando Café.
      Vous pouvez obtenir le jeton en rentrant à nouveau vos identifiant/mot de passe ici :
    </p>
    <form method="POST">
      {% csrf_token %}
      <label>Connexion</label>
      <input type="email" id="email">
      <input type="password" id="password">
      <input id="api-call" type="submit" value="Confirmer">
  </form>
  <p id="msg"></p>
  {% endif %}
  </div>
  {% load static %}
  <script src="{% static 'js/token.js' %}" defer></script>
{% endblock %}

randocafe/catalog/templates/catalog/roaster_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Formulaire d'édition d'un micro-torréfacteur</h1>
<form action="" method="post" class="tptForm">
  {% csrf_token %}
  <table>
    <tbody class="tabForm">
      <tr>
        <td>
          {{ form.as_table }}
        </td>
      </tr>
    </tbody>
  </table>
  <div class="btnForm">
    <input type="submit" value="Confirmer" />
    <a href="{% url 'roasters' %}">Annuler</a>
  </div>
</form>
{% endblock %}

randocafe/catalog/templates/catalog/trip_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Supprimer ce trip ?</h1>

<p>Êtes vous certain de vouloir supprimer ce trip de la base de données : {{ trip.name }} ?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Oui, supprimer" class="btnDelConf"/>
  <a href="{% url 'trips' %}" class="btnCA">Annuler</a>
</form>

{% endblock %}

randocafe/catalog/templates/catalog/trip_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Formulaire d'édition d'un trip</h1>
<form action="" method="post" class="tptForm">
  {% csrf_token %}
  <table>
    <tbody class="tabForm">
      <tr>
        <td>
          {{ form.as_table }}
        </td>
      </tr>
    </tbody>
  </table>
  <div class="btnForm">
    <input type="submit" value="Confirmer" />
    <a href="{% url 'trips' %}">Annuler</a>
  </div>
</form>
{% endblock %}

randocafe/catalog/templates/catalog/tripinstance_all_list_managed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Historique des toutes les réservations</h1>
    {% if tripinstance_list %}
        <ul>
        {% for instance in tripinstance_list %}
        <li class="{% if instance.passed_deadline %}text-danger{% endif %}">
            <a href="{% url 'tripinstance-detail' instance.pk %}">{{ instance.id }}</a>     - Propriétaire : {{instance.owner}} | Trip : {{ instance.trip.name }} | (Date de fin : {{ instance.end_date }})
                <!--|   <a href="{% url 'extend-trip-employee' instance.id %}">METTRE A JOUR DATE</a>  |-->
        </li>
        {% endfor %}
        </ul>

        {% else %}
        <p>Il n'y a pas encore de trip en gestion.</p>
    {% endif %}
{% endblock %}

randocafe/catalog/templates/catalog/tripinstance_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Formulaire d'édition d'une réservation</h1>
<form action="" method="post" class="tptForm">
  {% csrf_token %}
  <table>
    <tbody class="tabForm">
      <tr>
        <td>
          {{ form.as_table }}
        </td>
      </tr>
    </tbody>
  </table>
  <div class="btnForm">
    <input type="submit" value="Confirmer" />
    <a href="{% url 'tripinstances' %}">Annuler</a>
  </div>
</form>
{% endblock %}